spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: a1b2c3#A
  jackson:
    default-property-inclusion: non-null

jwt:
  secret: 01046a48-7a34-4df3-9299-099bda47cf9a
  expiration: 999999